//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.10.31 at 11:15:38 AM CET 
//


package be.abis.springsoapexercise.ws.model;

import org.springframework.stereotype.Component;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the be.abis.courses package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
@Component
public class ObjectFactory {

    private final static QName _ShortTitle_QNAME = new QName("http://abis.be/courses", "shortTitle");
    private final static QName _NumberOfDays_QNAME = new QName("http://abis.be/courses", "numberOfDays");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: be.abis.courses
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Course }
     * 
     */
    public Course createCourse() {
        return new Course();
    }

    /**
     * Create an instance of {@link Courses }
     * 
     */
    public Courses createCourses() {
        return new Courses();
    }

    /**
     * Create an instance of {@link CourseByShortTitleRequest }
     * 
     */
    public CourseByShortTitleRequest createCourseByShortTitleRequest() {
        return new CourseByShortTitleRequest();
    }

    /**
     * Create an instance of {@link CourseByShortTitleResponse }
     * 
     */
    public CourseByShortTitleResponse createCourseByShortTitleResponse() {
        return new CourseByShortTitleResponse();
    }

    /**
     * Create an instance of {@link CoursesByNumberOfDaysRequest }
     * 
     */
    public CoursesByNumberOfDaysRequest createCoursesByNumberOfDaysRequest() {
        return new CoursesByNumberOfDaysRequest();
    }

    /**
     * Create an instance of {@link CoursesByNumberOfDaysResponse }
     * 
     */
    public CoursesByNumberOfDaysResponse createCoursesByNumberOfDaysResponse() {
        return new CoursesByNumberOfDaysResponse();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://abis.be/courses", name = "shortTitle")
    public JAXBElement<String> createShortTitle(String value) {
        return new JAXBElement<String>(_ShortTitle_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}
     */
    @XmlElementDecl(namespace = "http://abis.be/courses", name = "numberOfDays")
    public JAXBElement<Integer> createNumberOfDays(Integer value) {
        return new JAXBElement<Integer>(_NumberOfDays_QNAME, Integer.class, null, value);
    }

}
